version: '2'

services:
  getting_data_out_of_microservices_db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/db.env
    ports:
      - '0.0.0.0:5432:5432'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    ports:
      - 9200:9200
